# Site settings
title: fabctory | microfactory | training | services
tag_text: fabctory 
description: recipes for innovation

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
